#!/usr/bin/env python3
"""Turn the "Low Poly Forest Tree Pack" (see assets/scenery/CREDITS.md) into the viewer's tree set.

Writes assets/scenery/trees/: one OBJ per tree part, scaled to 1 m tall with its base at
the origin, the textures they use (RGBA PNG, 1024 px, alpha = leaf cut-out) and trees.json:

    {"variants": [{"name", "kind": "conifer|broadleaf|bush", "parts": [{"mesh", "texture"}]}]}

usage: import_trees.py FOREST_PACK_DIR OUT_DIR
  FOREST_PACK_DIR   the unpacked pack (FOREST_TREE_PACK/, with SOURCE/ and TEXTURES/)
Needs Pillow.
"""
import json
import os
import sys

from PIL import Image

TEX = 1024


def frame_of(tris):
    """The frame that puts a tree 1 m tall with its trunk base at the origin."""
    ys = [v[0][1] for t in tris for v in t]
    y0, h = min(ys), max(ys) - min(ys)
    # centre on the lowest tenth (the trunk), not the crown
    low = [v[0] for t in tris for v in t if v[0][1] < y0 + 0.1 * h] or [v[0] for t in tris for v in t]
    cx = (min(p[0] for p in low) + max(p[0] for p in low)) / 2
    cz = (min(p[2] for p in low) + max(p[2] for p in low)) / 2
    return cx, y0, cz, h


def save_obj(path, tris, frame):
    """tris: list of (pos, uv, normal) triples."""
    cx, y0, cz, h = frame
    with open(path, "w") as f:
        f.write("# generated by tools/import_trees.py\n")
        for t in tris:
            for p, uv, n in t:
                f.write("v %.5f %.5f %.5f\n" % ((p[0] - cx) / h, (p[1] - y0) / h, (p[2] - cz) / h))
                f.write("vt %.5f %.5f\n" % uv)
                f.write("vn %.4f %.4f %.4f\n" % n)
        for i in range(len(tris)):
            a = 3 * i + 1
            f.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a, a, a, a + 1, a + 1, a + 1, a + 2, a + 2, a + 2))


def rgba(diffuse, opacity, out):
    im = Image.open(diffuse).convert("RGB")
    a = Image.open(opacity).convert("L") if opacity else None
    im = im.convert("RGBA")
    if a:
        im.putalpha(a.resize(im.size))
    im.resize((TEX, TEX), Image.LANCZOS).save(out, optimize=True)


def forest(src, out, variants):
    obj = os.path.join(src, "SOURCE", "Tree_Pack.obj")
    V, VT, VN, objs, cur = [], [], [], {}, None
    for line in open(obj):
        w = line.split()
        if not w:
            continue
        if w[0] == "v":
            V.append(tuple(map(float, w[1:4])))
        elif w[0] == "vt":
            VT.append(tuple(map(float, w[1:3])))
        elif w[0] == "vn":
            VN.append(tuple(map(float, w[1:4])))
        elif w[0] == "o":
            cur = w[1]
            objs[cur] = []
        elif w[0] == "f":
            idx = [tuple(int(x) - 1 for x in c.split("/")) for c in w[1:]]
            for k in range(1, len(idx) - 1):  # fan
                objs[cur].append([(V[a], VT[b], VN[c]) for a, b, c in (idx[0], idx[k], idx[k + 1])])
    tex = "forest_atlas.png"
    t = os.path.join(src, "TEXTURES", "TREES_LOW_POLY", "Background_Tree_Atlas_")
    rgba(t + "Diffuse.png", t + "Opacity.png", os.path.join(out, tex))
    # the background trees: 8 trees, then shrubs, ferns and grass
    names = ["Background_Tree_Atlas"] + ["Background_Tree_Atlas.%03d" % i for i in range(1, 13)]
    for i, name in enumerate(names):
        tris = objs[name]
        frame = frame_of(tris)
        mesh = "forest_%02d.obj" % i
        save_obj(os.path.join(out, mesh), tris, frame)
        kind = "bush" if i >= 8 else "tree"
        variants.append({"name": name, "kind": kind, "height": round(frame[3], 2), "parts": [{"mesh": mesh, "texture": tex}]})


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    out = sys.argv[2]
    os.makedirs(out, exist_ok=True)
    variants = []
    forest(sys.argv[1], out, variants)
    with open(os.path.join(out, "trees.json"), "w") as f:
        json.dump({"variants": variants}, f, indent=1)
    print("%d variants written to %s" % (len(variants), out))


if __name__ == "__main__":
    main()
